services:
  db:
    image: postgres:17-alpine
    container_name: insurance_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: insurance_db
    ports:
      - "5437:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: insurance_backend
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://admin:adminpassword@db:5432/insurance_db
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

volumes:
  postgres_data:

networks:
  claims_net:


