"""fresh_start

Revision ID: 8775727f1533
Revises: 
Create Date: 2025-04-05 21:30:07.031533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8775727f1533'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('claims',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('policy_number', sa.String(), nullable=False),
    sa.Column('claimant_name', sa.String(), nullable=False),
    sa.Column('claim_amount', sa.Float(), nullable=False),
    sa.Column('claimstatusenum', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'UNDER_REVIEW', name='claimstatusenum'), nullable=True),
    sa.Column('fraud_flag', sa.Boolean(), nullable=True),
    sa.Column('claim_date', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ocr_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('claim_id', sa.UUID(), nullable=False),
    sa.Column('extracted_text', sa.String(), nullable=False),
    sa.Column('document_path', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ocr_results')
    op.drop_table('claims')
    # ### end Alembic commands ###
