"""add proceessed to ocr table

Revision ID: b2a2e9b2b858
Revises: 8775727f1533
Create Date: 2025-04-06 07:37:50.974552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2a2e9b2b858'
down_revision: Union[str, None] = '8775727f1533'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ocr_results', sa.Column('processed', sa.Boolean(), nullable=True))
    op.add_column('ocr_results', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ocr_results', 'created_at')
    op.drop_column('ocr_results', 'processed')
    # ### end Alembic commands ###
